# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Nagisa Ariza"
footer_description: > # this means to ignore newlines until "baseurl:"
  Official website of Nagisa Ariza.
  © 2016 Nagisa Ariza, All Rights Reserved. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nagisaariza.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
description: >
  Having taught over 1000 students in the U.S. and Japan, Nagisa Ariza is 
  a professional pianist and music educator living in the San Francisco Bay Area.